echo normal
python extract_monocular_cues.py --task normal --img_path ../data/multiscan_monosdf/scan2/image --output_path ../data/multiscan_monosdf/scan2 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task normal --img_path ../data/multiscan_monosdf/scan3/image --output_path ../data/multiscan_monosdf/scan3 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task normal --img_path ../data/multiscan_monosdf/scan4/image --output_path ../data/multiscan_monosdf/scan4 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task normal --img_path ../data/multiscan_monosdf/scan5/image --output_path ../data/multiscan_monosdf/scan5 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task normal --img_path ../data/multiscan_monosdf/scan6/image --output_path ../data/multiscan_monosdf/scan6 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task normal --img_path ../data/multiscan_monosdf/scan7/image --output_path ../data/multiscan_monosdf/scan7 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task normal --img_path ../data/multiscan_monosdf/scan8/image --output_path ../data/multiscan_monosdf/scan8 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task normal --img_path ../data/multiscan_monosdf/scan9/image --output_path ../data/multiscan_monosdf/scan9 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task normal --img_path ../data/multiscan_monosdf/scan10/image --output_path ../data/multiscan_monosdf/scan10 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/

echo depth
python extract_monocular_cues.py --task depth --img_path ../data/multiscan_monosdf/scan1/image --output_path ../data/multiscan_monosdf/scan1 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task depth --img_path ../data/multiscan_monosdf/scan3/image --output_path ../data/multiscan_monosdf/scan3 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task depth --img_path ../data/multiscan_monosdf/scan4/image --output_path ../data/multiscan_monosdf/scan4 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task depth --img_path ../data/multiscan_monosdf/scan2/image --output_path ../data/multiscan_monosdf/scan2 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task depth --img_path ../data/multiscan_monosdf/scan5/image --output_path ../data/multiscan_monosdf/scan5 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task depth --img_path ../data/multiscan_monosdf/scan6/image --output_path ../data/multiscan_monosdf/scan6 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task depth --img_path ../data/multiscan_monosdf/scan7/image --output_path ../data/multiscan_monosdf/scan7 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task depth --img_path ../data/multiscan_monosdf/scan8/image --output_path ../data/multiscan_monosdf/scan8 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task depth --img_path ../data/multiscan_monosdf/scan9/image --output_path ../data/multiscan_monosdf/scan9 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
python extract_monocular_cues.py --task depth --img_path ../data/multiscan_monosdf/scan10/image --output_path ../data/multiscan_monosdf/scan10 --omnidata_path /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch --pretrained_models /home/sunxh/Xiaohao/omnidata/omnidata_tools/torch/pretrained_models/
